#!/bin/bash
if [ $# -ne 1 ]; then 
    echo "Usage: $0 <sceneID>"
    echo "Number of arguments: " $#
    exit 1
fi
SCENEID=$1
PORT=54324

echo PORT=${PORT}
echo SCENEID=${SCENEID}
OSCURL=osc.udp://226.0.0.1:${PORT}

set -o verbose

osc-send ${OSCURL} /SPIN/${SCENEID} clear
osc-send ${OSCURL} /SPIN/${SCENEID} clearUsers
sleep 0.1
osc-send ${OSCURL} /SPIN/${SCENEID} createNode grid GridNode

